### ISSUE TITLE
heals 1.5 hearts

### ISSUE THREAD

**Issue by MCPEPIG** [xxFlare/MushRoomStewHeal#2]
Um it heals 1.5 hearts instead of 3.5 hearts. I tryed with very low health (2 hearts) and it only healed 1.5 instead of 3.5

**Comment by xxFlare** [comment]
I will take a look at this. Thanks for reporting :D

**Comment by xxFlare** [comment]
Fixed. Thanks for reporting these issues as I would have not found them. If there are any more issues feel free to open another issue thread :)

**Comment by MCPEPIG** [comment]
Works now! :D
