### ISSUE TITLE
you can use them when u have full health

### ISSUE THREAD

**Issue by MCPEPIG** [xxFlare/MushRoomStewHeal#3]
Like the title says, you can use them when u have full hearts and u loose the stew and get a bowl.

**Comment by xxFlare** [comment]
Thanks for reporting this! I will fix it ASAP!

**Comment by xxFlare** [comment]
Alright, I pushed a fix to this. Let me know if it worked :)

**Comment by xxFlare** [comment]
Ok Im going to close this for now. Reopen it if you still have this issue.

**Comment by MCPEPIG** [comment]
Works now! :D
