### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by MCPEPIG** [xxFlare/MushRoomStewHeal#5]
When i got 1.3.0, it stopped working it didnt heal at all. I had it set to 3.5 for config.

**Comment by xxFlare** [comment]
Strange, I'll take a look. Thanks for reporting. :)

**Comment by MCPEPIG** [comment]
NP

**Comment by xxFlare** [comment]
I found the problem. It was a simple spelling mistake xD

Ill push a fix soon.

**Comment by xxFlare** [comment]
Alright, It should be fixed now.

**Comment by MCPEPIG** [comment]
Cool
